import os
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer

# --- USER: Add diverse queries for each subdomain ---
QUERIES = {
    "banking_law": [
        "What are the capital requirements for banks?",
        "How to apply for a banking license?",
        "What are the regulations for foreign banks?",
        "How to report suspicious transactions in banks?",
        "What are the penalties for banking violations?",
        "How to open a mobile banking unit?",
        "What are the rules for bank mergers?",
        "How to comply with anti-money laundering laws?",
        "What is the role of the Monetary Board?",
        "How to handle abandoned property in banks?",
        "What is the process for revoking a bank license?",
        "How are bank directors appointed?",
        "What is the minimum equity for a commercial bank?",
        "How to challenge a banking regulation?",
        "What is the deposit insurance scheme?",
        "How to establish a bank branch?",
        "What are the audit requirements for banks?",
        "How to close a foreign bank branch?",
        "What are the capital adequacy norms?",
        "How to merge two licensed banks?"
    ],
    "company_law": [
        "How do I register a new company?",
        "What are the duties of company directors?",
        "How can a company be amalgamated?",
        "What is the process for winding up a company?",
        "How are company articles of association amended?",
        "How to issue shares in a private company?",
        "What is a company prospectus?",
        "How to appoint a company secretary?",
        "What is the procedure for annual general meetings?",
        "How to transfer company shares?",
        "What are the requirements for company audits?",
        "How to change the company name?",
        "What is a derivative action in company law?",
        "How to remove a company director?",
        "What are the requirements for company records?",
        "How to register a foreign company?",
        "What is a holding company?",
        "How to file annual returns?",
        "How to increase company share capital?"
    ],
    "tax_law": [
        "How do I file a corporate tax return?",
        "What is the penalty for late tax payment?",
        "How are capital gains taxed?",
        "What are the exemptions under the Inland Revenue Act?",
        "How is withholding tax calculated?",
        "What is the arm's length principle?",
        "How to handle transfer pricing?",
        "What are the tax incentives for investments?",
        "How to register as a taxpayer?",
        "What are the procedures for tax audits?",
        "How to claim foreign tax credits?",
        "What is the process for tax appeals?",
        "How to pay advance income tax?",
        "What is the time limit for tax assessment?",
        "How to report tax evasion?",
        "What is the tax treatment of dividends?",
        "How to correct a tax return?",
        "What are the tax rates for individuals?",
        "How to handle tax on foreign income?"
    ],
    "arbitration_law": [
        "What is the arbitration procedure in Sri Lanka?",
        "How can an arbitral award be enforced?",
        "What are the grounds for setting aside an arbitration award?",
        "How to appoint an arbitrator?",
        "What is the role of the arbitration commission?",
        "How to file a request for arbitration?",
        "What are the rules for international arbitration?",
        "How to handle arbitration costs?",
        "What is the difference between mediation and arbitration?",
        "How to challenge an arbitration award?",
        "What is the limitation period for arbitration?",
        "How to consolidate arbitration proceedings?",
        "What is interim relief in arbitration?",
        "How to enforce a foreign arbitral award?",
        "What is the competence-competence principle?",
        "How to stay court proceedings for arbitration?",
        "What is the effect of an arbitration agreement?",
        "How to appeal an arbitral award?",
        "What are the confidentiality rules in arbitration?"
    ],
    "consumer_law": [
        "What rights do consumers have against unfair trade practices?",
        "How can a consumer file a complaint?",
        "What are anti-competitive practices?",
        "How to report false advertising?",
        "What are the penalties for consumer law violations?",
        "How to handle product recalls?",
        "What is the procedure for sale of perishable goods?",
        "How to resolve consumer disputes?",
        "What are the rules for consumer contracts?",
        "How to protect consumer data?",
        "How to claim a refund for defective goods?",
        "What is the cooling-off period for sales?",
        "How to report misleading packaging?",
        "What is the process for product liability claims?",
        "How to join a class action as a consumer?",
        "What are the rules for online consumer sales?",
        "How to check if a business is licensed?",
        "What are the penalties for price fixing?",
        "How to get compensation for faulty services?"
    ],
    "insolvency_law": [
        "What is the process for declaring bankruptcy?",
        "How are insolvent estates distributed?",
        "What are acts of insolvency?",
        "How to file a claim in insolvency?",
        "What are the duties of an assignee?",
        "How are dividends distributed in insolvency?",
        "What is the role of the Insolvency Board?",
        "How to handle fraudulent preferences?",
        "What are the consequences of insolvency?",
        "How to apply for composition after insolvency?",
        "What is a certificate of conformity?",
        "How to challenge an insolvency order?",
        "What is the process for voluntary liquidation?",
        "How to appoint a liquidator?",
        "What is the priority of creditor claims?",
        "How to recover assets from insolvent debtors?",
        "What is the effect of insolvency on contracts?",
        "How to annul an adjudication of insolvency?",
        "What are the offences in insolvency?"
    ],
    "ip_law": [
        "How to register a patent?",
        "What are the rights of performers?",
        "How to protect industrial designs?",
        "What is the duration of copyright?",
        "How to register a trademark?",
        "What are collective marks?",
        "How to handle IP infringement?",
        "What is unfair competition?",
        "How to apply for geographical indications?",
        "What are the penalties for IP violations?",
        "How to transfer IP rights?",
        "What is the process for patent opposition?",
        "How to enforce copyright?",
        "What is the Madrid Protocol?",
        "How to renew a trademark?",
        "What is a compulsory license?",
        "How to oppose a trademark application?",
        "What is the role of the IP office?",
        "How to register a design patent?"
    ],
    "negotiable_instruments_law": [
        "What is a bill of exchange?",
        "How to endorse a promissory note?",
        "What are the rules for cheques?",
        "How to handle dishonored bills?",
        "What is the liability of a banker?",
        "How to transfer negotiable instruments?",
        "What are the defenses against payment?",
        "How to present a bill for payment?",
        "What is the effect of acceptance?",
        "How to handle bills drawn in sets?",
        "How to protest a dishonored bill?",
        "What is the maturity date for a note?",
        "How to recover on a lost instrument?",
        "What is the statute of limitations for bills?",
        "How to stop payment on a cheque?",
        "What is the difference between a cheque and a draft?",
        "How to claim payment from a guarantor?",
        "What is a holder in due course?",
        "How to discharge a negotiable instrument?"
    ],
    "securities_law": [
        "What is insider trading?",
        "How to register a securities exchange?",
        "What are the duties of listed companies?",
        "How to issue a prospectus?",
        "What are the penalties for market manipulation?",
        "How to conduct a takeover?",
        "What is the role of the Securities Commission?",
        "How to handle unlisted securities?",
        "What are the rules for market intermediaries?",
        "How to recover damages for securities fraud?",
        "How to report securities fraud?",
        "What is a compensation fund in securities law?",
        "How to license a clearing house?",
        "What is a central depository?",
        "How to regulate public offers of securities?",
        "What are the rules for mergers in securities law?",
        "How to appeal a securities commission decision?",
        "What is the process for delisting?",
        "How to investigate insider trading?"
    ],
    "trust_law": [
        "What are the duties of a trustee?",
        "How to create a valid trust?",
        "What are charitable trusts?",
        "How to appoint and remove trustees?",
        "What are the rights of beneficiaries?",
        "How to handle constructive trusts?",
        "What is the role of the Trust Board?",
        "How to terminate a trust?",
        "What are the liabilities of trustees?",
        "How to manage trust assets?",
        "How to change a trust's purpose?",
        "What is a revocable trust?",
        "How to register a trust?",
        "What is a breach of trust?",
        "How to enforce a trust?",
        "What is a trust deed?",
        "How to distribute trust income?",
        "What are the tax implications for trusts?",
        "How to dissolve a trust?"
    ],
    "electronic_transactions_law": [
        "Are electronic contracts legally valid?",
        "What is the role of Certification Authorities?",
        "How to handle electronic signatures?",
        "What are the restrictions on electronic records?",
        "How to authenticate electronic documents?",
        "What is the liability of Certification Service Providers?",
        "How to designate a Certification Authority?",
        "What are the rules for data messages?",
        "How to handle electronic evidence?",
        "What are the exceptions for electronic transactions?",
        "How to dispute an electronic transaction?",
        "What is an electronic record?",
        "How to verify an electronic signature?",
        "What is a secure electronic document?",
        "How to submit documents electronically?",
        "What is the legal status of e-mails?",
        "How to store electronic records?",
        "What are the penalties for electronic fraud?",
        "How to conduct e-commerce legally?"
    ],
    "foreign_exchange_law": [
        "What are the authorized dealers in foreign exchange?",
        "How to remit foreign currency?",
        "What are the restrictions on capital transactions?",
        "How to report undeclared foreign exchange?",
        "What are the powers of the Central Bank?",
        "How to handle foreign exchange investigations?",
        "What are the penalties for foreign exchange violations?",
        "How to export and import foreign currency?",
        "What are the definitions of currency and securities?",
        "How to apply for foreign exchange authorization?",
        "How to open a foreign currency account?",
        "What is a restricted dealer?",
        "How to declare foreign assets?",
        "What is a capital transaction?",
        "How to repatriate foreign earnings?",
        "What is the process for foreign investment approval?",
        "How to comply with anti-money laundering in forex?",
        "What are the rules for cross-border payments?",
        "How to appeal a foreign exchange penalty?"
    ],
    "contract_law": [
        "What are the essential elements of a valid contract?",
        "How to draft a legally binding contract?",
        "What is the difference between a void and voidable contract?",
        "How to enforce a breach of contract?",
        "What are liquidated damages and penalties?",
        "How to terminate a contract?",
        "What is the doctrine of frustration?",
        "How to modify an existing contract?",
        "What is specific performance in contract law?",
        "What are implied terms in contracts?",
        "How to handle contracts with minors?",
        "What is undue influence in contract formation?",
        "How to rescind a contract?",
        "What is a unilateral contract?",
        "How to interpret ambiguous terms in a contract?",
        "What are exclusion clauses?",
        "What is privity of contract?",
        "How to prove contract acceptance?",
        "What are standard form contracts?"
    ]
}


def create_gating_dataset(output_csv="data/gating_train.csv", query_emb_dir="data/gating_queries/"):
    print("Preparing gating network training data...")
    os.makedirs(query_emb_dir, exist_ok=True)
    model = SentenceTransformer('all-MiniLM-L6-v2')
    
    data = []
    for label, qs in QUERIES.items():
        for i, q_text in enumerate(qs):
            emb = model.encode(q_text)
            emb_path = os.path.abspath(os.path.join(query_emb_dir, f"{label}_{i}.npy"))
            np.save(emb_path, emb)
            data.append({"query_embedding_path": emb_path, "expert_label": label})
            
    df = pd.DataFrame(data)
    df.to_csv(output_csv, index=False)
    print(f"Gating training data saved to {output_csv}")

if __name__ == "__main__":
    create_gating_dataset()