full_kg_data = {
    "nodes": [
        {"data": {"id": "contracts", "label": "contracts"}},
        {"data": {"id": "foundation for enforceable agreements", "label": "foundation for enforceable agreements"}},
        {"data": {"id": "valid contract", "label": "valid contract"}},
        {"data": {"id": "essential elements", "label": "essential elements"}},
        {"data": {"id": "legal frameworks", "label": "legal frameworks"}},
        {"data": {"id": "south african common law", "label": "south african common law"}},
        {"data": {"id": "consumer protection act 68 of 2008", "label": "consumer protection act 68 of 2008"}},
        {"data": {"id": "agreement between parties", "label": "agreement between parties"}},
        {"data": {"id": "intention to create legally binding obligations", "label": "intention to create legally binding obligations"}},
        {"data": {"id": "contractual capacity", "label": "contractual capacity"}},
        {"data": {"id": "lawful purpose", "label": "lawful purpose"}},
        {"data": {"id": "contract", "label": "contract"}},
        {"data": {"id": "contract to sell illegal goods", "label": "contract to sell illegal goods"}},
        {"data": {"id": "void", "label": "void"}},
        {"data": {"id": "principles", "label": "principles"}},
        {"data": {"id": "global standards", "label": "global standards"}},
        {"data": {"id": "consensus and legality", "label": "consensus and legality"}},
        {"data": {"id": "unidroit principles of international commercial contracts (2016)", "label": "unidroit principles of international commercial contracts (2016)"}},
        {"data": {"id": "oral or written", "label": "oral or written"}},
        {"data": {"id": "specific contracts", "label": "specific contracts"}},
        {"data": {"id": "in writing and signed", "label": "in writing and signed"}},
        {"data": {"id": "alienation of land act 68 of 1981", "label": "alienation of land act 68 of 1981"}},
        {"data": {"id": "writing requirement for land sales", "label": "writing requirement for land sales"}},
        {"data": {"id": "national credit act 34 of 2005", "label": "national credit act 34 of 2005"}},
        {"data": {"id": "writing requirement for credit agreements", "label": "writing requirement for credit agreements"}},
        {"data": {"id": "long-term leases", "label": "long-term leases"}},
        {"data": {"id": "writing", "label": "writing"}},
        {"data": {"id": "contracts of suretyship", "label": "contracts of suretyship"}},
        {"data": {"id": "executory donations", "label": "executory donations"}},
        {"data": {"id": "marriage contracts", "label": "marriage contracts"}},
        {"data": {"id": "fourie v. hansen (2000)", "label": "fourie v. hansen (2000)"}},
        {"data": {"id": "necessity of written agreements for land transactions", "label": "necessity of written agreements for land transactions"}},
        {"data": {"id": "breach of contract", "label": "breach of contract"}},
        {"data": {"id": "party fails to fulfill obligations", "label": "party fails to fulfill obligations"}},
        {"data": {"id": "restatement (second) of contracts (1981)", "label": "restatement (second) of contracts (1981)"}},
        {"data": {"id": "breach as failure to perform", "label": "breach as failure to perform"}},
        {"data": {"id": "delivering defective goods", "label": "delivering defective goods"}},
        {"data": {"id": "partial performance", "label": "partial performance"}},
        {"data": {"id": "refusing to deliver goods", "label": "refusing to deliver goods"}},
        {"data": {"id": "repudiation", "label": "repudiation"}},
        {"data": {"id": "remedies for breach", "label": "remedies for breach"}},
        {"data": {"id": "restore aggrieved party’s position", "label": "restore aggrieved party’s position"}},
        {"data": {"id": "specific performance", "label": "specific performance"}},
        {"data": {"id": "court-ordered fulfillment of obligations", "label": "court-ordered fulfillment of obligations"}},
        {"data": {"id": "hayne v. kingwilliamstown municipality (1951)", "label": "hayne v. kingwilliamstown municipality (1951)"}},
        {"data": {"id": "specific performance when monetary compensation inadequate", "label": "specific performance when monetary compensation inadequate"}},
        {"data": {"id": "an interdict", "label": "an interdict"}},
        {"data": {"id": "further breaches", "label": "further breaches"}},
        {"data": {"id": "damages", "label": "damages"}},
        {"data": {"id": "losses", "label": "losses"}},
        {"data": {"id": "cancellation with damages", "label": "cancellation with damages"}},
        {"data": {"id": "contract termination", "label": "contract termination"}},
        {"data": {"id": "consumer protection act", "label": "consumer protection act"}},
        {"data": {"id": "contract cancellation", "label": "contract cancellation"}},
        {"data": {"id": "fulfillment of obligations", "label": "fulfillment of obligations"}},
        {"data": {"id": "mutual agreement", "label": "mutual agreement"}},
        {"data": {"id": "material breach", "label": "material breach"}},
        {"data": {"id": "death of a party", "label": "death of a party"}},
        {"data": {"id": "expiry of contract period", "label": "expiry of contract period"}},
        {"data": {"id": "unidroit principles", "label": "unidroit principles"}},
        {"data": {"id": "termination for fundamental non-performance", "label": "termination for fundamental non-performance"}},
        {"data": {"id": "south african practices", "label": "south african practices"}},
        {"data": {"id": "cancellation", "label": "cancellation"}},
        {"data": {"id": "lease agreement", "label": "lease agreement"}},
        {"data": {"id": "expiry", "label": "expiry"}},
        {"data": {"id": "specified term’s expiry", "label": "specified term’s expiry"}},
        {"data": {"id": "mutual obligations", "label": "mutual obligations"}},
        {"data": {"id": "reciprocal duties", "label": "reciprocal duties"}},
        {"data": {"id": "seller", "label": "seller"}},
        {"data": {"id": "goods", "label": "goods"}},
        {"data": {"id": "buyer", "label": "buyer"}},
        {"data": {"id": "price", "label": "price"}},
        {"data": {"id": "reciprocity", "label": "reciprocity"}},
        {"data": {"id": "roman-dutch law principle of synallagma", "label": "roman-dutch law principle of synallagma"}},
        {"data": {"id": "post-signing", "label": "post-signing"}},
        {"data": {"id": "national credit act", "label": "national credit act"}},
        {"data": {"id": "written amendments", "label": "written amendments"}},
        {"data": {"id": "mutual consent", "label": "mutual consent"}},
        {"data": {"id": "unilateral alterations", "label": "unilateral alterations"}},
        {"data": {"id": "condition precedent", "label": "condition precedent"}},
        {"data": {"id": "event", "label": "event"}},
        {"data": {"id": "non-performing party", "label": "non-performing party"}},
        {"data": {"id": "consequences", "label": "consequences"}},
        {"data": {"id": "unilateral termination", "label": "unilateral termination"}},
        {"data": {"id": "specific circumstances", "label": "specific circumstances"}},
        {"data": {"id": "aggrieved party to cancel", "label": "aggrieved party to cancel"}},
        {"data": {"id": "impossibility", "label": "impossibility"}},
        {"data": {"id": "termination", "label": "termination"}},
        {"data": {"id": "contract law", "label": "contract law"}},
        {"data": {"id": "south african statutes", "label": "south african statutes"}},
        {"data": {"id": "case law", "label": "case law"}},
        {"data": {"id": "international frameworks", "label": "international frameworks"}}
    ],
    "edges": [
        {"source": "contracts", "target": "foundation for enforceable agreements", "relation": "serve as"},
        {"source": "contracts", "target": "oral or written", "relation": "can be"},
        {"source": "contracts", "target": "fulfillment of obligations", "relation": "terminate through"},
        {"source": "contracts", "target": "mutual agreement", "relation": "terminate through"},
        {"source": "contracts", "target": "material breach", "relation": "terminate through"},
        {"source": "contracts", "target": "death of a party", "relation": "terminate through"},
        {"source": "contracts", "target": "expiry of contract period", "relation": "terminate through"},
        {"source": "contracts", "target": "post-signing", "relation": "can be modified"},
        {"source": "valid contract", "target": "essential elements", "relation": "requires"},
        {"source": "valid contract", "target": "legal frameworks", "relation": "outlined in"},
        {"source": "essential elements", "target": "agreement between parties", "relation": "include"},
        {"source": "essential elements", "target": "intention to create legally binding obligations", "relation": "include"},
        {"source": "essential elements", "target": "contractual capacity", "relation": "include"},
        {"source": "essential elements", "target": "lawful purpose", "relation": "include"},
        {"source": "legal frameworks", "target": "south african common law", "relation": "include"},
        {"source": "legal frameworks", "target": "consumer protection act 68 of 2008", "relation": "include"},
        {"source": "contract", "target": "lawful purpose", "relation": "must have"},
        {"source": "contract to sell illegal goods", "target": "void", "relation": "would be"},
        {"source": "principles", "target": "global standards", "relation": "align with"},
        {"source": "global standards", "target": "consensus and legality", "relation": "emphasize"},
        {"source": "global standards", "target": "unidroit principles of international commercial contracts (2016)", "relation": "include"},
        {"source": "specific contracts", "target": "in writing and signed", "relation": "must be"},
        {"source": "alienation of land act 68 of 1981", "target": "writing requirement for land sales", "relation": "stipulates"},
        {"source": "national credit act 34 of 2005", "target": "writing requirement for credit agreements", "relation": "stipulates"},
        {"source": "long-term leases", "target": "writing", "relation": "require"},
        {"source": "contracts of suretyship", "target": "writing", "relation": "require"},
        {"source": "executory donations", "target": "writing", "relation": "require"},
        {"source": "marriage contracts", "target": "writing", "relation": "require"},
        {"source": "fourie v. hansen (2000)", "target": "necessity of written agreements for land transactions", "relation": "upheld"},
        {"source": "breach of contract", "target": "party fails to fulfill obligations", "relation": "occurs"},
        {"source": "restatement (second) of contracts (1981)", "target": "breach as failure to perform", "relation": "defines"},
        {"source": "delivering defective goods", "target": "partial performance", "relation": "constitutes"},
        {"source": "refusing to deliver goods", "target": "repudiation", "relation": "signals"},
        {"source": "remedies for breach", "target": "restore aggrieved party’s position", "relation": "aim"},
        {"source": "specific performance", "target": "court-ordered fulfillment of obligations", "relation": "is"},
        {"source": "hayne v. kingwilliamstown municipality (1951)", "target": "specific performance when monetary compensation inadequate", "relation": "shows"},
        {"source": "an interdict", "target": "further breaches", "relation": "prevents"},
        {"source": "damages", "target": "losses", "relation": "compensate"},
        {"source": "cancellation with damages", "target": "contract termination", "relation": "allows"},
        {"source": "consumer protection act", "target": "contract cancellation", "relation": "governs"},
        {"source": "material breach", "target": "aggrieved party to cancel", "relation": "allows"},
        {"source": "unidroit principles", "target": "termination for fundamental non-performance", "relation": "allow"},
        {"source": "south african practices", "target": "cancellation", "relation": "justify"},
        {"source": "lease agreement", "target": "expiry", "relation": "ends upon"},
        {"source": "lease agreement", "target": "specified term’s expiry", "relation": "ends"},
        {"source": "mutual obligations", "target": "reciprocal duties", "relation": "refer to"},
        {"source": "seller", "target": "goods", "relation": "delivers"},
        {"source": "buyer", "target": "price", "relation": "pays"},
        {"source": "reciprocity", "target": "roman-dutch law principle of synallagma", "relation": "rooted in"},
        {"source": "national credit act", "target": "written amendments", "relation": "mandates"},
        {"source": "mutual consent", "target": "unilateral alterations", "relation": "prevents"},
        {"source": "condition precedent", "target": "event", "relation": "is"},
        {"source": "non-performing party", "target": "consequences", "relation": "bears"},
        {"source": "unilateral termination", "target": "specific circumstances", "relation": "is permissible"},
        {"source": "impossibility", "target": "termination", "relation": "justifies"},
        {"source": "contract law", "target": "south african statutes", "relation": "draws from"},
        {"source": "contract law", "target": "case law", "relation": "draws from"},
        {"source": "contract law", "target": "international frameworks", "relation": "draws from"}
    ]
}